# Generated by Django 3.1.5 on 2021-01-14 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
