# Generated by Django 3.1.5 on 2021-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210118_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
